### ISSUE TITLE
Symfony 6.1 deprecations

### ISSUE THREAD

**Issue by qkdreyer** [php-enqueue/enqueue-dev#1270]
```
  1x: The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "Enqueue\Symfony\Consumption\ConfigurableConsumeCommand".

  1x: The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "Enqueue\Symfony\Client\ConsumeCommand".

  1x: The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "Enqueue\Symfony\Client\ProduceCommand".

  1x: The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "Enqueue\Symfony\Client\SetupBrokerCommand".

  1x: The "Symfony\Component\Console\Command\Command::$defaultName" property is considered final. You should not override it in "Enqueue\Symfony\Client\RoutesCommand".

  1x: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Enqueue\Symfony\Consumption\ConfigurableConsumeCommand" class instead.

  1x: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Enqueue\Symfony\Client\ConsumeCommand" class instead.

  1x: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Enqueue\Symfony\Client\ProduceCommand" class instead.

  1x: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Enqueue\Symfony\Client\SetupBrokerCommand" class instead.

  1x: Since symfony/console 6.1: Relying on the static property "$defaultName" for setting a command name is deprecated. Add the "Symfony\Component\Console\Attribute\AsCommand" attribute to the "Enqueue\Symfony\Client\RoutesCommand" class instead.
 ```

**Comment by phillipsb22** [comment]
May I please get this assigned to me

**Comment by VincentLanglet** [comment]
Solved by https://github.com/php-enqueue/enqueue-dev/pull/1311 and release in 0.10.20

**Comment by zyv4yk** [comment]
this notices are still present, I've made Pr to solve this 
https://github.com/php-enqueue/enqueue-dev/pull/1350

**Comment by makasim** [comment]
https://github.com/php-enqueue/enqueue-dev/pull/1362
